=== TimetoTreatment/XML-Editor/PartManager.dtd
<!ENTITY NVDA "NVIDIA">
<!ENTITY % monetary_unit 'unit (KRW | USD) "USD"'>

<!ELEMENT Parts (VGA:VGA*, CPU:CPU*)>
<!ATTLIST Parts xmlns:xsi CDATA #IMPLIED>
<!ATTLIST Parts xsi:schemaLocation CDATA #IMPLIED>
<!ATTLIST Parts xmlns CDATA #IMPLIED>
<!ATTLIST Parts xmlns:VGA CDATA #IMPLIED>
<!ATTLIST Parts xmlns:CPU CDATA #IMPLIED>
<!ATTLIST Parts xmlns:part CDATA #IMPLIED>

<!ATTLIST VGA:VGA id CDATA #REQUIRED>
<!ELEMENT VGA:VGA (part:name, part:manufacturer, part:series, part:launch_date, part:msrp, VGA:specs)>

<!ELEMENT part:name (#PCDATA)>
<!ELEMENT part:manufacturer (#PCDATA)>
<!ELEMENT part:series (#PCDATA)>
<!ELEMENT part:launch_date (#PCDATA)>
<!ELEMENT part:msrp (#PCDATA)>
<!ATTLIST part:msrp %monetary_unit;>

<!ELEMENT VGA:specs (VGA:core_num, VGA:memory_size, VGA:power_consumption, VGA:slot_size?)>

<!ELEMENT VGA:core_num (#PCDATA)>
<!ELEMENT VGA:memory_size (#PCDATA)>
<!ATTLIST VGA:memory_size type CDATA #REQUIRED>
<!ELEMENT VGA:power_consumption (#PCDATA)>
<!ELEMENT VGA:slot_size (#PCDATA)>

<!ATTLIST CPU:CPU id CDATA #REQUIRED>
<!ELEMENT CPU:CPU (part:name, part:manufacturer, part:series, part:launch_date, part:msrp, CPU:specs)>

<!ELEMENT CPU:specs (CPU:core_num, CPU:frequency, CPU:power_consumption, CPU:integrated_graphics?)>

<!ELEMENT CPU:core_num (#PCDATA)>
<!ELEMENT CPU:frequency (#PCDATA)>
<!ELEMENT CPU:power_consumption (#PCDATA)>
<!ELEMENT CPU:integrated_graphics (#PCDATA)>

=== TimetoTreatment/XML-Editor/kaka.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Parts SYSTEM "PartManager.dtd">
<?xml-stylesheet type="text/xsl" href="PartManager.xsl"?><Parts xmlns="http://PartManager.com" xmlns:CPU="http://PartManager.com/parts/CPU" xmlns:VGA="http://PartManager.com/parts/VGA" xmlns:part="http://PartManager.com/part" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://PartManager.com PartManager.xsd">
    <!--=================-->
    <!--== List of VGA ==-->
    <!--=================-->
    <!--NVIDIA, GeForce RTX 30 series-->
    <VGA:VGA id="kakapo">
        <part:name>GeForce RTX 3090</part:name>
        <part:manufacturer>NVIDIA</part:manufacturer>
        <part:series>GeForce RTX 30</part:series>
        <part:launch_date>2020-09-24</part:launch_date>
        <part:msrp unit="USD">1499</part:msrp>
        <VGA:specs>
            <VGA:core_num>10496</VGA:core_num>
            <VGA:memory_size type="GDDR6X">24</VGA:memory_size>
            <VGA:power_consumption>350</VGA:power_consumption>
            <VGA:slot_size>3</VGA:slot_size>
        </VGA:specs>
    </VGA:VGA>
    <VGA:VGA id="n2">
        <part:name>GeForce RTX 3080</part:name>
        <part:manufacturer>NVIDIA</part:manufacturer>
        <part:series>GeForce RTX 30</part:series>
        <part:launch_date>2020-09-17</part:launch_date>
        <part:msrp unit="KRW">699000</part:msrp>
        <VGA:specs>
            <VGA:core_num>8704</VGA:core_num>
            <VGA:memory_size type="GDDR6X">10</VGA:memory_size>
            <VGA:power_consumption>320</VGA:power_consumption>
            <VGA:slot_size>2</VGA:slot_size>
        </VGA:specs>
    </VGA:VGA>
    <VGA:VGA id="n1">
        <part:name>GeForce RTX 3080 Ti</part:name>
        <part:manufacturer>NVIDIA</part:manufacturer>
        <part:series>GeForce RTX 30</part:series>
        <part:launch_date>2021-06-03</part:launch_date>
        <part:msrp unit="USD">1199</part:msrp>
        <VGA:specs>
            <VGA:core_num>10240</VGA:core_num>
            <VGA:memory_size type="GDDR6X">12</VGA:memory_size>
            <VGA:power_consumption>350</VGA:power_consumption>
            <VGA:slot_size>2</VGA:slot_size>
        </VGA:specs>
    </VGA:VGA>
    <VGA:VGA id="n3">
        <part:name>GeForce RTX 3070 Ti</part:name>
        <part:manufacturer>NVIDIA</part:manufacturer>
        <part:series>GeForce RTX 30</part:series>
        <part:launch_date>2021-06-10</part:launch_date>
        <part:msrp unit="USD">599</part:msrp>
        <VGA:specs>
            <VGA:core_num>6144</VGA:core_num>
            <VGA:memory_size type="GDDR6X">8</VGA:memory_size>
            <VGA:power_consumption>290</VGA:power_consumption>
            <VGA:slot_size>2</VGA:slot_size>
        </VGA:specs>
    </VGA:VGA>
    <VGA:VGA id="n4">
        <part:name>GeForce RTX 3070</part:name>
        <part:manufacturer>NVIDIA</part:manufacturer>
        <part:series>GeForce RTX 30</part:series>
        <part:launch_date>2020-10-29</part:launch_date>
        <part:msrp unit="USD">499</part:msrp>
        <VGA:specs>
            <VGA:core_num>5888</VGA:core_num>
            <VGA:memory_size type="GDDR6">8</VGA:memory_size>
            <VGA:power_consumption>220</VGA:power_consumption>
            <VGA:slot_size>2</VGA:slot_size>
        </VGA:specs>
    </VGA:VGA>
    <VGA:VGA id="n5">
        <part:name>GeForce RTX 3060 Ti</part:name>
        <part:manufacturer>NVIDIA</part:manufacturer>
        <part:series>GeForce RTX 30</part:series>
        <part:launch_date>2020-12-02</part:launch_date>
        <part:msrp unit="USD">399</part:msrp>
        <VGA:specs>
            <VGA:core_num>4864</VGA:core_num>
            <VGA:memory_size type="GDDR6">8</VGA:memory_size>
            <VGA:power_consumption>200</VGA:power_consumption>
            <VGA:slot_size>2</VGA:slot_size>
        </VGA:specs>
    </VGA:VGA>
    <VGA:VGA id="n6">
        <part:name>GeForce RTX 3060</part:name>
        <part:manufacturer>NVIDIA</part:manufacturer>
        <part:series>GeForce RTX 30</part:series>
        <part:launch_date>2021-02-25</part:launch_date>
        <part:msrp unit="USD">329</part:msrp>
        <VGA:specs>
            <VGA:core_num>3584</VGA:core_num>
            <VGA:memory_size type="GDDR6">12</VGA:memory_size>
            <VGA:power_consumption>170</VGA:power_consumption>
            <VGA:slot_size>2</VGA:slot_size>
        </VGA:specs>
    </VGA:VGA>
    <!--NVIDIA, GeForce GTX 16 series-->
    <VGA:VGA id="n7">
        <part:name>GeForce GTX 1660 Ti</part:name>
        <part:manufacturer>NVIDIA</part:manufacturer>
        <part:series>GeForce GTX 16</part:series>
        <part:launch_date>2019-02-22</part:launch_date>
        <part:msrp unit="USD">279</part:msrp>
        <VGA:specs>
            <VGA:core_num>1536</VGA:core_num>
            <VGA:memory_size type="GDDR6">6</VGA:memory_size>
            <VGA:power_consumption>120</VGA:power_consumption>
            <VGA:slot_size>2</VGA:slot_size>
        </VGA:specs>
    </VGA:VGA>
    <VGA:VGA id="n8">
        <part:name>GeForce GTX 1660</part:name>
        <part:manufacturer>NVIDIA</part:manufacturer>
        <part:series>GeForce GTX 16</part:series>
        <part:launch_date>2019-03-14</part:launch_date>
        <part:msrp unit="USD">219</part:msrp>
        <VGA:specs>
            <VGA:core_num>1408</VGA:core_num>
            <VGA:memory_size type="GDDR5">6</VGA:memory_size>
            <VGA:power_consumption>120</VGA:power_consumption>
            <VGA:slot_size>2</VGA:slot_size>
        </VGA:specs>
    </VGA:VGA>
    <VGA:VGA id="n9">
        <part:name>GeForce GTX 1650 Super</part:name>
        <part:manufacturer>NVIDIA</part:manufacturer>
        <part:series>GeForce GTX 16</part:series>
        <part:launch_date>2019-11-22</part:launch_date>
        <part:msrp unit="USD">159</part:msrp>
        <VGA:specs>
            <VGA:core_num>1280</VGA:core_num>
            <VGA:memory_size type="GDDR6">4</VGA:memory_size>
            <VGA:power_consumption>100</VGA:power_consumption>
            <VGA:slot_size>2</VGA:slot_size>
        </VGA:specs>
    </VGA:VGA>
    <VGA:VGA id="n10">
        <part:name>GeForce GTX 1650</part:name>
        <part:manufacturer>NVIDIA</part:manufacturer>
        <part:series>GeForce GTX 16</part:series>
        <part:launch_date>2019-04-23</part:launch_date>
        <part:msrp unit="USD">149</part:msrp>
        <VGA:specs>
            <VGA:core_num>896</VGA:core_num>
            <VGA:memory_size type="GDDR5">4</VGA:memory_size>
            <VGA:power_consumption>75</VGA:power_consumption>
        </VGA:specs>
    </VGA:VGA>
    <!--AMD, Radeon RX 6000 series-->
    <VGA:VGA id="a1">
        <part:name>Radeon RX 6900 XT</part:name>
        <part:manufacturer>AMD</part:manufacturer>
        <part:series>Radeon RX 6000</part:series>
        <part:launch_date>2020-12-08</part:launch_date>
        <part:msrp unit="USD">999</part:msrp>
        <VGA:specs>
            <VGA:core_num>5120</VGA:core_num>
            <VGA:memory_size type="GDDR6">16</VGA:memory_size>
            <VGA:power_consumption>300</VGA:power_consumption>
            <VGA:slot_size>2.5</VGA:slot_size>
        </VGA:specs>
    </VGA:VGA>
    <VGA:VGA id="a2">
        <part:name>Radeon RX 6800 XT</part:name>
        <part:manufacturer>AMD</part:manufacturer>
        <part:series>Radeon RX 6000</part:series>
        <part:launch_date>2020-11-18</part:launch_date>
        <part:msrp unit="USD">649</part:msrp>
        <VGA:specs>
            <VGA:core_num>4608</VGA:core_num>
            <VGA:memory_size type="GDDR6">16</VGA:memory_size>
            <VGA:power_consumption>300</VGA:power_consumption>
            <VGA:slot_size>2.5</VGA:slot_size>
        </VGA:specs>
    </VGA:VGA>
    <VGA:VGA id="a3">
        <part:name>Radeon RX 6800</part:name>
        <part:manufacturer>AMD</part:manufacturer>
        <part:series>Radeon RX 6000</part:series>
        <part:launch_date>2020-11-18</part:launch_date>
        <part:msrp unit="USD">579</part:msrp>
        <VGA:specs>
            <VGA:core_num>3840</VGA:core_num>
            <VGA:memory_size type="GDDR6">16</VGA:memory_size>
            <VGA:power_consumption>250</VGA:power_consumption>
            <VGA:slot_size>2</VGA:slot_size>
        </VGA:specs>
    </VGA:VGA>
    <VGA:VGA id="a4">
        <part:name>Radeon RX 6700 XT</part:name>
        <part:manufacturer>AMD</part:manufacturer>
        <part:series>Radeon RX 6000</part:series>
        <part:launch_date>2021-03-18</part:launch_date>
        <part:msrp unit="USD">479</part:msrp>
        <VGA:specs>
            <VGA:core_num>2560</VGA:core_num>
            <VGA:memory_size type="GDDR6">12</VGA:memory_size>
            <VGA:power_consumption>230</VGA:power_consumption>
            <VGA:slot_size>2</VGA:slot_size>
        </VGA:specs>
    </VGA:VGA>
    <VGA:VGA id="a5">
        <part:name>Radeon RX 6600 XT</part:name>
        <part:manufacturer>AMD</part:manufacturer>
        <part:series>Radeon RX 6000</part:series>
        <part:launch_date>2021-08-11</part:launch_date>
        <part:msrp unit="USD">379</part:msrp>
        <VGA:specs>
            <VGA:core_num>2048</VGA:core_num>
            <VGA:memory_size type="GDDR6">8</VGA:memory_size>
            <VGA:power_consumption>160</VGA:power_consumption>
        </VGA:specs>
    </VGA:VGA>
    <VGA:VGA id="a6">
        <part:name>Radeon RX 6600</part:name>
        <part:manufacturer>AMD</part:manufacturer>
        <part:series>Radeon RX 6000</part:series>
        <part:launch_date>2021-10-13</part:launch_date>
        <part:msrp unit="USD">329</part:msrp>
        <VGA:specs>
            <VGA:core_num>1792</VGA:core_num>
            <VGA:memory_size type="GDDR6">8</VGA:memory_size>
            <VGA:power_consumption>132</VGA:power_consumption>
        </VGA:specs>
    </VGA:VGA>

    <!--=================-->
    <!--== List of CPU ==-->
    <!--=================-->
    <!--Intel, 9th Gen-->
    <CPU:CPU id="i1">
